### ISSUE TITLE
Unexpected result for srgb with rgb fraction values?

### ISSUE THREAD

**Issue by greghuc** [colorjs/color-rgba#7]
Hi there

Is this the expected behaviour for `color-rgba`? I can't tell if it's a bug or not :-)

Input :   `color(srgb 0.85098 0.121569 0.160784)`
Output: `[0.85098, 0.121569, 0.160784, 1]`

I had expected the result to be an array with values normalised between 0-255 for rgb, and 0-1 for a: `rgba(217,31,41,1) ` (which I got by multiplying the rgb values by 255 and rounding)

I ask, as I'm trying to normalise browser-computed css color values into a standard form for comparison. So for this case, the `color-rgba` output isn't useful, as it's not the 0-255 rgb form.

Many thanks

Greg

**Comment by dy** [comment]
Hi @greghuc. Not sure I understand your case. Can you give exact code you run color-rgba function with? I can't reproduce any of the examples you give. color-rgba doesn't do normalization, it just parses string into array as is essentially. If you need normalization, use [color-normalize](https://github.com/colorjs/color-normalize).

**Comment by greghuc** [comment]
@dy thanks for the fast reply. `color-normalize` seems more like what I am looking for. Closing.
